### PR TITLE
Milestone 5

### PR DESCRIPTION
**Pull request by pbkabali**
## What this PR does:
- Adds styling to the different app components
- Adds simple validation for creation of the book
- Adds a default message for empty filtered results
- Updates the README file

[Live App](https://dry-garden-92123.herokuapp.com/)

### CODE REVIEW

**Review by SpaYco — CHANGES_REQUESTED** [review]
# Changes Requested 

Hello Team! 👋 
Awesome job so far!! 👍 you still need to make some changes though! 

## Required Changes ♻️ 

- [ ] Please do not use images for the percentage circles, implement it as HTML or SVG ([this pen might help](https://codepen.io/sergiopedercini/pen/jmKdbj))

### please make the appropriate changes and ask for another code review ✔️ 

Happy Coding!

Best, 
Aziz Mejri 
_contact me on [twitter](https://twitter.com/iSpaYco) or slack (@SpaYco) if you need any help_

**Comment by pbkabali** [comment]
Thanks, @Spayco for the review and good advice. I have made changes and requested another review

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Well done @pbkabali! You may proceed to the next milestone.
__[Note]__ The categories section in the header is where the filter should finally be placed.

__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by pbkabali** [comment]
Dear @trekab, I appreciate your review. Thanks a lot

**Pull request merged**
